[rustsync]
# 初始管理员密码，仅首次创建数据库时生效；RANDOM或空值表示随机生成
password=RANDOM
# 运行端口号
port=8023
# 登录有效期，单位天
expires=9999
# 日志等级：0-DEBUG，1-INFO，2-WARNING，3-ERROR，4-CRITICAL
log_level=1
# 控制台日志等级
console_level=2
# 系统日志保留天数，0表示不自动清理
log_save=7
# 任务记录保留天数，0表示不自动清理
task_save=0
# 任务执行超时时间，单位小时
task_timeout=72
