name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'version (e.g. v1.0.1)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

env:
  APP_NAME: RustSync

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    if: github.ref != 'refs/tags/v1.1.0'
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Determine Version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            TAG_VERSION="${{ github.event.inputs.version }}"
          else
            TAG_VERSION=${GITHUB_REF#refs/tags/}
          fi
          VERSION=${TAG_VERSION#v}
          echo "tag=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $TAG_VERSION ($VERSION)"

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [get-version]
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22.x"
          cache: npm
          cache-dependency-path: rustsync/web/package-lock.json
      - name: Build Frontend
        working-directory: rustsync/web
        run: |
          sed -i "s/__version_placeholder__/$VERSION/g" src/locales/zh-CN.yaml
          sed -i "s/__version_placeholder__/$VERSION/g" src/locales/en.yaml
          npm ci
          npm run build
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: rustsync/web/dist
          retention-days: 1
